### ISSUE TITLE
failing tests for develop branch

### ISSUE THREAD

**Issue by carocad** [asyncapi/node-codegen#1]
After cloning the repo, installing it and then running `npm run test` I get a failure message

```
Invalid JSON obtained from the content of the AsyncAPI specification file
[ { code: 'OBJECT_ADDITIONAL_PROPERTIES',
    params: [ [Array] ],
    message: 'Additional properties not allowed: schemes,host',
    path: '#/',
    schemaId: 'http://asyncapi.hitchhq.com/v1/schema.json#' } ]
(node:59724) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'baseTopic' of undefined
    at module.exports (/Users/Camilo/Documents/eWorkspace/node-codegen/lib/beautifier.js:26:33)
    at codegen.process (/Users/Camilo/Documents/eWorkspace/node-codegen/lib/codegen.js:8:20)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:59724) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:59724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any idea what might be causing this?

**Comment by fmvilas** [comment]
Thanks for raising it. It's failing because the root properties `schemes` and `host` are not part of AsyncAPI anymore. I'll update the package to use the servers object instead.

**Comment by fmvilas** [comment]
It is now fixed, released and on npm @carocad. Thanks!
